export const EVENT_GROUP_NAME = "EVENT_GROUP_NAME"

export const QUEUE_HIGH_PRIORITY = 1
export const QUEUE_MEDIUM_PRIORITY = 2
export const QUEUE_LOW_PRIORITY = 3

export const ATTEMPT_COUNT_NORMAL = (20 * 60) / 4
export const ATTEMPT_COUNT_EXTENDED = 3 * ATTEMPT_COUNT_NORMAL
export const ATTEMPT_COUNT_ULTIMATE = 12 * ATTEMPT_COUNT_NORMAL
